DELIMITER //

CREATE PROCEDURE CriaPontosCnefe()
BEGIN
  -- 1. Criar a tabelaCriaPontosCnefe
  CREATE TABLE IF NOT EXISTS PontosCnefe (
    COD_UNICO_ENDERECO VARCHAR(20),
    COD_UF VARCHAR(2),
    COD_MUNICIPIO VARCHAR(7),
    COD_DISTRITO VARCHAR(10),
    COD_SUBDISTRITO VARCHAR(12),
    COD_SETOR VARCHAR(17),
    NUM_QUADRA VARCHAR(3),
    NUM_FACE VARCHAR(3),
    CEP VARCHAR(8),
    DSC_LOCALIDADE VARCHAR(100),
    NOM_TIPO_SEGLOGR VARCHAR(50),
    NOM_TITULO_SEGLOGR VARCHAR(50),
    NOM_SEGLOGR VARCHAR(100),
    NUM_ENDERECO VARCHAR(10),
    DSC_MODIFICADOR VARCHAR(50),
    NOM_COMP_ELEM1 VARCHAR(50),
    VAL_COMP_ELEM1 VARCHAR(50),
    NOM_COMP_ELEM2 VARCHAR(50),
    VAL_COMP_ELEM2 VARCHAR(50),
    NOM_COMP_ELEM3 VARCHAR(50),
    VAL_COMP_ELEM3 VARCHAR(50),
    NOM_COMP_ELEM4 VARCHAR(50),
    VAL_COMP_ELEM4 VARCHAR(50),
    NOM_COMP_ELEM5 VARCHAR(50),
    VAL_COMP_ELEM5 VARCHAR(50),
    LATITUDE DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6),
    NV_GEO_COORD VARCHAR(20),
    COD_ESPECIE VARCHAR(20),
    DSC_ESTABELECIMENTO VARCHAR(50),
    COD_INDICADOR_ESTAB_ENDERECO VARCHAR(10),
    COD_INDICADOR_CONST_ENDERECO VARCHAR(10),
    COD_INDICADOR_FINALIDADE_CONST VARCHAR(10),
    COD_TIPO_ESPECI VARCHAR(10),
    COORDS_PONTO GEOMETRY
  );
END //

DELIMITER ;
