CREATE TABLE IF NOT EXISTS CI_LOTES (
	COD_MUNICIPIO              VARCHAR(7),
	COD_UNICO_ENDERECO         VARCHAR(25),
	NUM_QUADRA                 VARCHAR(25),
	NOM_LOGRADOURO             VARCHAR(250),
	NUM_ENDERECO               VARCHAR(25),
	NOM_LOGRADOURO_ADJACENTE   VARCHAR(250),
	DIM_TESTADA                DECIMAL(6,2),
	DIM_PROFUNDIDADE           DECIMAL(6,2),
	AREA			   DECIMAL(6,2)	
);

CREATE TABLE IF NOT EXISTS CI_LOGRADOUROS (
	SC_ID_LOGRADOURO        VARCHAR(8),
	COD_MUNICIPIO           VARCHAR(7),
	CI_NOM_LOGRADOURO_NORM  VARCHAR(250),
	CI_NOM_LOGRADOURO       VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS CI_FACES (
	ID_FACE                 VARCHAR(50),
	COD_MUNICIPIO           VARCHAR(7),
	NUM_QUADRA              VARCHAR(25),
	SC_ID_LOGRADOURO        VARCHAR(8),
	QTD_LOTES               INT,
	DIMENSAO                DECIMAL(6,2)
);

CREATE TABLE IF NOT EXISTS CI_ADJACENTES (
	ID_FACE           	VARCHAR(65),
	COD_MUNICIPIO     	VARCHAR(7),
	ID_QUADRA         	VARCHAR(50),
	SC_ID_LOGRADOURO  	VARCHAR(8),
	DIM_ADJACENTE     	DECIMAL(6,2)     
);

CREATE TABLE IF NOT EXISTS CI_QUADRAS (
	ID_QUADRA         	VARCHAR(50),
	COD_MUNICIPIO 		VARCHAR(7),
	SC_ID_QUADRA 		VARCHAR(250),
	QTD_PONTOS 		INT,
	AREA 			DECIMAL(16,2)
);


