CREATE TABLE IF NOT EXISTS CI_LOTES (
	COD_MUNICIPIO           	VARCHAR(7),
	COD_UNICO_ENDERECO      	VARCHAR(25),
	NUM_QUADRA              	VARCHAR(25),
	NOM_LOGRADOURO      	VARCHAR(250),
	NUM_ENDERECO            	VARCHAR(25),
	NOM_LOGRADOURO_ADJACENTE VARCHAR(250),
	DIM_TESTADA              DECIMAL(6,2),
	DIM_PROFUNDIDADE         DECIMAL(6,2),
	AREA			   		DECIMAL(6,2)	
);

CREATE TABLE IF NOT EXISTS CI_LOGRADOUROS (
	SC_ID_LOGRADOURO        	VARCHAR(8),
	COD_MUNICIPIO           	VARCHAR(7),
	CI_NOM_LOGRADOURO_NORM  	VARCHAR(250),
	CI_NOM_LOGRADOURO       	VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS CI_FACES (
	CI_ID_FACE               VARCHAR(37),
	COD_MUNICIPIO           	VARCHAR(7),
	CI_ID_QUADRA            	VARCHAR(20),
	SC_ID_LOGRADOURO        	VARCHAR(8),
	QTD_LOTES               	INT,
	DIM_FACE               	DECIMAL(6,2)
);

CREATE TABLE IF NOT EXISTS CI_ADJACENTES (
	CI_ID_FACE		   	VARCHAR(37),
	COD_MUNICIPIO		   	VARCHAR(7),
	CI_ID_QUADRA		   	VARCHAR(20),
	SC_ID_LOGRADOURO	   	VARCHAR(8),
	CI_COD_UNICO_ENDERECO  	VARCHAR(25),
	DIM_ADJACENTE		   	DECIMAL(6,2)  
);

CREATE TABLE IF NOT EXISTS CI_QUADRAS (
	CI_ID_QUADRA         	VARCHAR(20),
	COD_MUNICIPIO 			VARCHAR(7),
	SC_ID_QUADRA 			VARCHAR(250),
	QTD_LOTES 			INT,
	AREA 				DECIMAL(16,2)
);




