-- Remove dados antigos do município para evitar duplicidade
DELETE FROM CI_LOTES WHERE COD_MUNICIPIO = '${COD_MUNICIPIO}';

-- Executa a carga massiva via Stream
LOAD DATA LOCAL INFILE '${ARQUIVO_CSV}'
INTO TABLE CI_LOTES
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(
	COD_MUNICIPIO,
	COD_UNICO_ENDERECO,
	NUM_QUADRA,
	NOM_LOGRADOURO,
	NUM_ENDERECO,
	NOM_LOGRADOURO_ADJACENTE,
	@DIM_TESTADA,
	@DIM_PROFUNDIDADE
)
SET
	DIM_TESTADA = REPLACE(@DIM_TESTADA, ',', '.'),
	DIM_PROFUNDIDADE = REPLACE(@DIM_PROFUNDIDADE, ',', '.');