SET NAMES 'utf8';
-- Função para preencher CI_LOGRADOUROS
DELETE FROM CI_LOGRADOUROS WHERE COD_MUNICIPIO = ${cod_municipio};
INSERT INTO CI_LOGRADOUROS (
	COD_MUNICIPIO, 
	CI_NOM_LOGRADOURO_NORM,
	CI_NOM_LOGRADOURO,
	SC_ID_LOGRADOURO
)
SELECT DISTINCT
	LT.COD_MUNICIPIO,
	REGEXP_REPLACE(TRIM(UPPER(LT.NOM_LOGRADOURO)), '[[:space:]]{2,}', ' ') AS CI_NOM_LOGRADOURO_NORM,
	LT.NOM_LOGRADOURO AS CI_NOM_LOGRADOURO,
	NULL AS SC_ID_LOGRADOURO
FROM CI_LOTES LT;



	

