-- Função para atualizar CI_LOGRADOUROS
UPDATE smuu.CI_LOGRADOUROS AS CI
	JOIN smuu.CN_LOGRADOUROS AS CN
		ON 	CI.CI_NOM_LOGRADOURO_NORM = CN.NOM_LOGRADOURO 
		AND 	CI.COD_MUNICIPIO = CN.COD_MUNICIPIO
SET CI.SC_ID_LOGRADOURO = CN.SC_ID_LOGRADOURO
WHERE 
	(CI.COD_MUNICIPIO = '${cod_municipio}')
	AND 	(CI.SC_ID_LOGRADOURO IS NULL);
	

-- Atualizando as faces em CI_FACE
DELETE FROM CI_FACES WHERE COD_MUNICIPIO = '${cod_municipio}';
INSERT INTO CI_FACES (
    CI_ID_FACE, 
    COD_MUNICIPIO, 
    CI_ID_QUADRA, 
    SC_ID_LOGRADOURO, 
    QTD_LOTES, 
    DIM_FACE
)
SELECT 
    CONCAT(
      LT.COD_MUNICIPIO, ";", LT.NUM_QUADRA, ";", LG.SC_ID_LOGRADOURO
    ) AS CI_ID_FACE,
    LT.COD_MUNICIPIO, 
    LT.NUM_QUADRA AS CI_ID_QUADRA, 
    LG.SC_ID_LOGRADOURO,
    COUNT(*) AS QTD_LOTES,           -- Conta lotes existem da face
    SUM(LT.DIM_TESTADA) AS DIM_FACE  -- Soma a testada total da face
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG 
    ON 	(LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
    AND	(LT.COD_MUNICIPIO = LG.COD_MUNICIPIO)
GROUP BY 
    LT.COD_MUNICIPIO, 
    LT.NUM_QUADRA, 
    LG.SC_ID_LOGRADOURO;

		
		
-- Atualizando as faces em ADJACENTES
DELETE FROM CI_ADJACENTES WHERE COD_MUNICIPIO = '${cod_municipio}';
INSERT INTO CI_ADJACENTES (
	CI_ID_FACE, 
	COD_MUNICIPIO, 
	CI_ID_QUADRA, 
	SC_ID_LOGRADOURO, 
	CI_COD_UNICO_ENDERECO,
	DIM_ADJACENTE ) 
SELECT DISTINCT 
	CONCAT(
		LT.COD_MUNICIPIO, ";", LT.NUM_QUADRA, ";", LG.SC_ID_LOGRADOURO
	) AS CI_ID_FACE,
	LT.COD_MUNICIPIO, 
	NUM_QUADRA AS CI_ID_QUADRA, 
	SC_ID_LOGRADOURO,
	COD_UNICO_ENDERECO AS CI_COD_UNICO_ENDERECO, 
	DIM_PROFUNDIDADE AS DIM_ADJACENTE 
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG 
	ON 	(LT.NOM_LOGRADOURO_ADJACENTE = LG.CI_NOM_LOGRADOURO)
	AND 	(LT.COD_MUNICIPIO = LG.COD_MUNICIPIO)
WHERE (NOM_LOGRADOURO_ADJACENTE <> "");
	


-- Atualizando DIM_FACE com as dimensões de CI_ADJACENTES
UPDATE CI_FACES F
INNER JOIN (
    -- Agrupa-se os valores por CI_ID_FACE para evitar múltiplas somas 
    SELECT 
        CI_ID_FACE, 
        SUM(DIM_ADJACENTE) AS TOTAL_ADJACENTE
    FROM CI_ADJACENTES
    GROUP BY CI_ID_FACE
) A ON F.CI_ID_FACE = A.CI_ID_FACE
SET F.DIM_FACE = F.DIM_FACE + A.TOTAL_ADJACENTE;



-- Preenchendo as quadras em CI_QUADRAS
DELETE FROM CI_QUADRAS WHERE COD_MUNICIPIO = '${cod_municipio}';
INSERT INTO CI_QUADRAS (
	CI_ID_QUADRA, COD_MUNICIPIO, SC_ID_QUADRA, 
	QTD_LOTES, AREA
)
SELECT 
	CI_ID_QUADRA,
	COD_MUNICIPIO,
	CONCAT('[', 
		GROUP_CONCAT(SC_ID_LOGRADOURO 
		ORDER BY SC_ID_LOGRADOURO 
		SEPARATOR ','), 
	']') AS SC_ID_QUADRA,
	SUM(QTD_LOTES) AS QTD_LOTES,
	0.00 AS AREA
FROM CI_FACES
GROUP BY 
	COD_MUNICIPIO, 
	CI_ID_QUADRA;  
