CREATE TABLE IF NOT EXISTS CN_PONTOS (
	COD_UNICO_ENDERECO 		VARCHAR(20),
	COD_UF 				VARCHAR(2),
	COD_MUNICIPIO 			VARCHAR(9),
	COD_SUBDISTRITO 		VARCHAR(11),
	COD_SETOR 			VARCHAR(16),
	NUM_QUADRA 			VARCHAR(7),
	COD_DISTRITO 			VARCHAR(3),
	NUM_FACE 			VARCHAR(3),
	CEP 				VARCHAR(8),
	DSC_LOCALIDADE 			VARCHAR(50),
	NOM_TIPO_SEGLOGR 		VARCHAR(50),
	NOM_TITULO_SEGLOGR 		VARCHAR(50),
	NOM_SEGLOGR 			VARCHAR(50),
	NUM_ENDERECO 			VARCHAR(10),
	DSC_MODIFICADOR 		VARCHAR(20),
	NOM_COMP_ELEM1 			VARCHAR(20),
	VAL_COMP_ELEM1 			VARCHAR(20),
	NOM_COMP_ELEM2 			VARCHAR(20),
	VAL_COMP_ELEM2 			VARCHAR(20),
	NOM_COMP_ELEM3 			VARCHAR(20),
	VAL_COMP_ELEM3 			VARCHAR(20),
	NOM_COMP_ELEM4 			VARCHAR(20),
	VAL_COMP_ELEM4 			VARCHAR(20),
	NOM_COMP_ELEM5 			VARCHAR(20),
	VAL_COMP_ELEM5 			VARCHAR(20),
	LATITUDE 			DECIMAL(10,8),
	LONGITUDE 			DECIMAL(10,8),
	NV_GEO_COORD 			VARCHAR(10),
	COD_ESPECIE 			VARCHAR(10),
	DSC_ESTABELECIMENTO 		VARCHAR(100),
	COD_INDICADOR_ESTAB_ENDERECO 	VARCHAR(10),
	COD_INDICADOR_CONST_ENDERECO 	VARCHAR(10),
	COD_INDICADOR_FINALIDADE_CONST 	VARCHAR(10),
	COD_TIPO_ESPECI 		VARCHAR(10)
);


CREATE TABLE IF NOT EXISTS CN_PONTOS_UNICOS (
	COD_MUNICIPIO        VARCHAR(7),
	COD_UNICO_ENDERECO   VARCHAR(20),
	ID_QUADRA            VARCHAR(19),
	ID_FACE              VARCHAR(22),
	NOM_LOGRADOURO       VARCHAR(250),
	NUM_ENDERECO         VARCHAR(10),
	LATITUDE             DECIMAL(10,8),
	LONGITUDE            DECIMAL(11,8),
	COORDS               POINT
);

CREATE TABLE IF NOT EXISTS CN_LOGRADOUROS (
	COD_MUNICIPIO        VARCHAR(7),
	NOM_LOGRADOURO       VARCHAR(250),
	SC_ID_LOGRADOURO     VARCHAR(8), 
	COORDS               TEXT
);

CREATE TABLE IF NOT EXISTS CN_FACES (
	ID_FACE           VARCHAR(22),
	COD_MUNICIPIO     VARCHAR(7),
	ID_QUADRA         VARCHAR(19),
	NOM_LOGRADOURO    VARCHAR(250),
	SC_ID_LOGRADOURO  VARCHAR(8),
	NR_ORDEM          INT,
	QTD_PONTOS        INT,
	CENTROIDE         POINT
);

CREATE TABLE IF NOT EXISTS CN_QUADRAS (
	SC_ID_QUADRA        VARCHAR(250),
	COD_MUNICIPIO       VARCHAR(7),
	ID_QUADRA           VARCHAR(19),
	QTD_PONTOS          INT,
	CENTROIDE           POINT
);
  
  