
-- Exclui tabelas temporárias
DROP TABLE IF EXISTS TMP_ENDERECOS_BASE;
DROP TABLE IF EXISTS TMP_ENDERECOS_UNICOS;

-- Primeira etapa: Cria tabela temporária consolidando endereços
CREATE TABLE TMP_ENDERECOS_BASE AS
SELECT 
	COD_MUNICIPIO,
	COD_UNICO_ENDERECO,
	CONCAT(COD_SETOR, LPAD(NUM_QUADRA, 3, '0')) AS ID_QUADRA,
	CONCAT(COD_SETOR, LPAD(NUM_QUADRA, 3, '0'), LPAD(NUM_FACE, 3, '0')) AS ID_FACE,
	TRIM(
		CONCAT_WS(' ',
			NULLIF(TRIM(NOM_TIPO_SEGLOGR), ''),
		  	NULLIF(TRIM(NOM_TITULO_SEGLOGR), ''),
		 	NULLIF(TRIM(NOM_SEGLOGR), '')
		)
	) AS NOM_LOGRADOURO,
	NUM_ENDERECO,
	LATITUDE,
	LONGITUDE
FROM CN_PONTOS
WHERE 
  NV_GEO_COORD < '4'
	 AND 
  NUM_QUADRA > 0;

-- Segunda etapa: Agrupamento para eliminação de duplicidades e cálculo de centroides
-- MySQL 10.2
CREATE TABLE TMP_ENDERECOS_UNICOS AS
SELECT 
	COD_MUNICIPIO,
	NOM_LOGRADOURO,
	NUM_ENDERECO,
	AVG(LATITUDE) AS LATITUDE_MEDIA,
	AVG(LONGITUDE) AS LONGITUDE_MEDIA,
	COUNT(*) AS QTD_PONTOS,
	-- Identificação da Quadra e Face predominantes (Moda Estatística)
	SUBSTRING_INDEX(
		GROUP_CONCAT(ID_QUADRA ORDER BY ID_QUADRA SEPARATOR ','), 
		',', 1
	) AS ID_QUADRA_MODA,
	SUBSTRING_INDEX(
		GROUP_CONCAT(ID_FACE ORDER BY ID_FACE SEPARATOR ','), 
		',', 1
	) AS ID_FACE_MODA,
	MIN(COD_UNICO_ENDERECO) AS COD_UNICO_ENDERECO_REF
FROM TMP_ENDERECOS_BASE
GROUP BY 
	 COD_MUNICIPIO, 
	 NOM_LOGRADOURO, 
	 NUM_ENDERECO;


-- Insere os endereços únicos na tabela final
-- MySQL 10.2
DELETE FROM CN_PONTOS_UNICOS WHERE COD_MUNICIPIO = ${cod_municipio};
INSERT INTO CN_PONTOS_UNICOS (
	COD_MUNICIPIO, 
	COD_UNICO_ENDERECO, 
	ID_QUADRA, 
	ID_FACE, 
	NOM_LOGRADOURO, 
	NUM_ENDERECO, 
	LATITUDE, 
	LONGITUDE, 
	COORDS
)
SELECT 
	COD_MUNICIPIO,
	COD_UNICO_ENDERECO_REF,
	ID_QUADRA_MODA,
	ID_FACE_MODA,
	NOM_LOGRADOURO,
	NUM_ENDERECO,
	LATITUDE_MEDIA,
	LONGITUDE_MEDIA,
	POINT(LONGITUDE_MEDIA, LATITUDE_MEDIA)
FROM TMP_ENDERECOS_UNICOS;


-- Função para preencher CN_LOGRADOUROS
DELETE FROM CN_LOGRADOUROS WHERE COD_MUNICIPIO = ${cod_municipio};
INSERT INTO CN_LOGRADOUROS (
	COD_MUNICIPIO, 
	NOM_LOGRADOURO, 
	SC_ID_LOGRADOURO, 
	COORDS
)
SELECT 
	COD_MUNICIPIO,
	NOM_LOGRADOURO,
	LPAD(HEX(CRC32(CONCAT(COD_MUNICIPIO, NOM_LOGRADOURO))), 8, '0') AS SC_ID_LOGRADOURO,
	""
FROM CN_PONTOS_UNICOS
WHERE COD_MUNICIPIO = ${cod_municipio}  
GROUP BY COD_MUNICIPIO, NOM_LOGRADOURO;


-- Função para preencher CN_FACES
DELETE FROM CN_FACES WHERE COD_MUNICIPIO = ${cod_municipio};
INSERT INTO CN_FACES (
	ID_FACE, 
	COD_MUNICIPIO, 
	ID_QUADRA,
	NOM_LOGRADOURO, 
	SC_ID_LOGRADOURO, 
	NR_ORDEM, 
	QTD_PONTOS, 
	CENTROIDE
)
SELECT
	ID_FACE,
	COD_MUNICIPIO,
	ID_QUADRA,
	NOM_LOGRADOURO,
	"",
	CAST(SUBSTRING(ID_FACE FROM LENGTH(ID_FACE) - 2) AS INTEGER),
	COUNT(*) AS QTD_PONTOS,
	POINT(AVG(LONGITUDE), AVG(LATITUDE)) AS CENTROIDE
FROM CN_PONTOS_UNICOS
GROUP BY ID_FACE;

-- Função para complementar CN_FACES
UPDATE 	CN_FACES AS f
JOIN 	CN_LOGRADOUROS AS l
  	ON 	f.COD_MUNICIPIO = l.COD_MUNICIPIO
      		AND TRIM(UPPER(f.NOM_LOGRADOURO)) = TRIM(UPPER(l.NOM_LOGRADOURO))
SET 	f.SC_ID_LOGRADOURO = l.SC_ID_LOGRADOURO
WHERE 	f.SC_ID_LOGRADOURO IS NULL 
  	OR f.SC_ID_LOGRADOURO = '';


-- Função para preencher CN_QUADRAS
DELETE FROM CN_QUADRAS WHERE COD_MUNICIPIO = ${cod_municipio};
INSERT INTO CN_QUADRAS (
	SC_ID_QUADRA, 
	COD_MUNICIPIO, 
	ID_QUADRA, 
	QTD_PONTOS, 
	CENTROIDE)
SELECT 
	-- SC_ID_QUADRA
	CONCAT('[', 
		GROUP_CONCAT(COALESCE(f.SC_ID_LOGRADOURO, '')
		ORDER BY f.SC_ID_LOGRADOURO 
		SEPARATOR ','), 
		']'
	) AS SC_ID_QUADRA,
	f.COD_MUNICIPIO,
	f.ID_QUADRA,
	SUM(f.QTD_PONTOS) AS QTD_PONTOS,
	-- Calcular centroide manualmente (média das coordenadas)
	ST_GEOMFROMTEXT(
		CONCAT(
		'POINT(',
		AVG(ST_X(f.CENTROIDE)),
		' ',
		AVG(ST_Y(f.CENTROIDE)),
		')')
	) AS CENTROIDE
FROM 
	CN_FACES f
	WHERE 
		f.SC_ID_LOGRADOURO IS NOT NULL
		AND f.SC_ID_LOGRADOURO != ''
	GROUP BY 
		f.ID_QUADRA, 
		f.COD_MUNICIPIO
	ORDER BY 
	 	f.COD_MUNICIPIO, 
		f.ID_QUADRA;