CREATE TABLE IF NOT EXISTS OSM_LOGRADOUROS (
	OSM_ID 			BIGINT(20),
	SC_ID_LOGRADOURO	VARCHAR(8),
	NOM_LOGRADOURO		VARCHAR(255),
	OSM_NOM_LOGRADOURO	VARCHAR(255),
	GEOMETRIA		LINESTRING	-- Geometria consolidada	
);

CREATE TABLE IF NOT EXISTS OSM_CONSULTAS (
    SC_ID_LOGRADOURO VARCHAR(8) PRIMARY KEY,
    CN_NOM_LOGRADOURO VARCHAR(250),
    OSM_NOM_LOGRADOURO VARCHAR(250),
    COD_MUNICIPIO VARCHAR(7),
    RESPOSTA_OSM_JSON LONGTEXT, -- Resposta bruta da Fase 1
    DATA_CONSULTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);