CREATE TABLE IF NOT EXISTS OSM_LOGRADOUROS (
	OSM_ID 			BIGINT(20),
	SC_ID_LOGRADOURO	VARCHAR(8),
	NOM_LOGRADOURO		VARCHAR(255),
	OSM_NOM_LOGRADOURO	VARCHAR(255),
	GEOMETRIA		LINESTRING	-- Geometria consolidada	
);

CREATE TABLE IF NOT EXISTS OSM_CONSULTAS (
    SC_ID_LOGRADOURO 	VARCHAR(8) PRIMARY KEY,
    CN_NOM_LOGRADOURO 	VARCHAR(250), -- Nome na base original
    OSM_NOM_LOGRADOURO 	VARCHAR(250), -- Nome retornado pelo OSM
    RESPOSTA_OSM 		LONGTEXT,           -- JSON completo (geometria + tags)
    DATA_CONSULTA 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);