CREATE TABLE IF NOT EXISTS OSM_LOGRADOUROS (
	OSM_ID 			BIGINT(20),
	SC_ID_LOGRADOURO	VARCHAR(8),
	NOM_LOGRADOURO		VARCHAR(255),
	OSM_NOM_LOGRADOURO	VARCHAR(255),
	GEOMETRIA		LINESTRING	-- Geometria consolidada	
);
