-- Log de importação
CREATE TABLE IF NOT EXISTS SC_LOG (
	COD_MUNICIPIO 	  	VARCHAR(7),
	NOM_MUNICIPIO		VARCHAR(128),	
	TP_ARQUIVO		VARCHAR(128),
	QT_REGISTROS 		INT,
	DT_IMPORTACAO   	DATE
);


CREATE TABLE IF NOT EXISTS SC_FACES (
	SC_ID_FACE	 	VARCHAR(258), /* SC_ID_QUADRA + SC_ID_LOGRADOURO */
	COD_MUNICIPIO 	  	VARCHAR(7),
	SC_ID_QUADRA 		VARCHAR(250),
	SC_ID_LOGRADOURO	VARCHAR(8),
	CN_ID_FACE	        VARCHAR(22),
	CENTROIDE           	POINT,
	ORDEM_FACE        	INT(11),
	CI_ID_FACE       	VARCHAR(65),
	DIM_FACE		FLOAT,
	QTD_LOTES		INT(11)
);


CREATE TABLE IF NOT EXISTS SC_QUADRAS (
	SC_ID_QUADRA 		VARCHAR(250),
	COD_MUNICIPIO 	  	VARCHAR(7),
	CI_ID_QUADRA       	VARCHAR(50),
	CN_ID_QUADRA       	VARCHAR(19),
	CENTROIDE           	POINT
);


CREATE TABLE IF NOT EXISTS SC_PARCELAS (
	SC_ID_PARCELA 		VARCHAR(33), 	-- COD_MINICIPIO + ";" + TRIM(CI_ID_LOTE)
	SC_ID_FACE	        VARCHAR(259),
	SC_ID_QUADRA 		VARCHAR(250),
	SC_ID_LOGRADOURO	VARCHAR(8),
	COD_MUNICIPIO 	  	VARCHAR(7),
	CI_ID_LOTE		VARCHAR(22),	-- TRIM(CI_LOTES.COD_UNICO_ENDERECO)
	CI_ID_FACE		VARCHAR(67),
	CI_ID_QUADRA		VARCHAR(20),
	NUM_ENDERECO		VARCHAR(10),	-- TRIM(CI_LOTES.COD_NUM_ENDERECO)	
	DIM_TESTADA         	FLOAT,
	DIM_PROFUNDIDADE   	FLOAT,
	COORD_PARCELA		POLYGON
);



  