SELECT * FROM smuu.CI_LOTES;

CREATE TABLE IF NOT EXISTS CI_FACES (
         ID_FACE                       VARCHAR(28),
         COD_MUNICIPIO                 VARCHAR(7),
         NUM_QUADRA                    VARCHAR(20),
         SC_ID_LOGRADOURO              VARCHAR(8),
         CI_NOM_LOGRADOURO             VARCHAR(250),
         QTD_LOTES                     INT,
         DIMENSAO                      FLOAT
    );
      
CREATE TABLE IF NOT EXISTS CI_QUADRAS (
		ID_QUADRA 			varchar(19),
		COD_MUNICIPIO 		varchar(7),
		SC_ID_QUADRA 		varchar(250),
		QTD_LOTES 			int(11)
	);

CREATE TABLE IF NOT EXISTS SC_QUADRAS (
		SC_ID_QUADRA 		varchar(250),
		COD_MUNICIPIO 		varchar(7),
		ORDEM_FACES 		varchar(250),
        CENTROIDE_FACES		varchar(500),
        DIM_FACES			varchar(250),
		QTD_FACES			int(11)
	);

INSERT INTO SC_QUADRAS (ID_FACE, COD_MUNICIPIO, ID_QUADRA,
	NOM_LOGRADOURO, QTD_PONTOS, CENTROIDE)
SELECT
	ID_FACE,
	COD_MUNICIPIO,
	ID_QUADRA,
	NOM_LOGRADOURO,
	COUNT(*) AS QTD_PONTOS,
	POINT(AVG(LONGITUDE), AVG(LATITUDE)) AS CENTROIDE
FROM CN_PONTOS_UNICOS
GROUP BY ID_FACE;

SELECT * FROM CN_QUADRAS CN
JOIN CI_QUADRAS CI
	ON (CI.COD_MUNICIPIO = CN.COD_MUNICIPIO)
		AND
	(CI.SC_ID_QUADRA = CN.SC_ID_QUADRA)
;
	
SELECT count(*)
FROM CI_LOGRADOUROS
WHERE
	SC_ID_LOGRADOURO IS NOT NULL
	-- AND COD_MUNICIPIO = '4104501'
;

SELECT DISTINCT COD_MUNICIPIO,NOM_LOGRADOURO,NUM_ENDERECO
FROM CI_LOTES
WHERE COD_MUNICIPIO = '4104501';

SELECT COUNT(*)
FROM CN_PONTOS_UNICOS 
WHERE COD_MUNICIPIO = '4104501';

DROP TABLE IF EXISTS SOUNDEX;
CREATE temporary TABLE SOUNDEX
SELECT NOM_LOGRADOURO, CI_NOM_LOGRADOURO_NORM 
	FROM CN_LOGRADOUROS CN
	JOIN CI_LOGRADOUROS CI
		ON ( SOUNDEX(CI.CI_NOM_LOGRADOURO_NORM) = SOUNDEX(CN.NOM_LOGRADOURO))
WHERE CI.SC_ID_LOGRADOURO IS NULL	
;

SELECT * FROM SOUNDEX;

