SELECT * FROM smuu.CI_LOTES 
;

SELECT * FROM smuu.CI_LOGRADOUROS
;

SELECT 
	DISTINCT 
    CONCAT(LT.COD_MUNICIPIO, NUM_QUADRA, SC_ID_LOGRADOURO) AS ID_FACE,
    LT.COD_MUNICIPIO, NUM_QUADRA, NOM_LOGRADOURO, SC_ID_LOGRADOURO
FROM CI_LOTES LT
JOIN
	CI_LOGRADOUROS LG
    ON 
		(LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
;

SELECT 
    CONCAT(LT.COD_MUNICIPIO, NUM_QUADRA, SC_ID_LOGRADOURO) AS ID_FACE,
    LT.COD_MUNICIPIO, 
    NUM_QUADRA, 
    NOM_LOGRADOURO, 
    SC_ID_LOGRADOURO,
    SUM(LT.DIM_TESTADA) AS TOTAL_TESTADA
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG
    ON (LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
GROUP BY 
    LT.COD_MUNICIPIO, 
    NUM_QUADRA, 
    NOM_LOGRADOURO, 
    SC_ID_LOGRADOURO
;
    
-- Atualizando as quadras em CI_LOTES
-- quando a ID_QUADRA não está disponível no cadastro municipal
-- Usar somente para fins acadêmicos
DROP TABLE IF EXISTS CI_LOTES_;
CREATE TEMPORARY TABLE CI_LOTES_
SELECT 
	LT.COD_MUNICIPIO,
    LT.COD_UNICO_ENDERECO,
    LT.NUM_QUADRA,
    LT.NOM_LOGRADOURO,
    LT.NUM_ENDERECO,
    NOM_LOGRADOURO_ADJACENTE,
    DIM_TESTADA,
    DIM_PROFUNDIDADE,
	LG.SC_ID_LOGRADOURO
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG
	ON (LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
;
SELECT *
FROM CI_LOTES_
;

CREATE TEMPORARY TABLE CN_PONTOS_UNICOS_
SELECT 
	PU.COD_MUNICIPIO,
    LG.NOM_LOGRADOURO,
    LG.SC_ID_LOGRADOURO,
    PU.NUM_ENDERECO,
    PU.ID_QUADRA
FROM CN_PONTOS_UNICOS PU
JOIN CN_LOGRADOUROS LG
	ON (PU.NOM_LOGRADOURO = LG.NOM_LOGRADOURO)
;
SELECT *
FROM CN_PONTOS_UNICOS_
;

SELECT
	LT.COD_MUNICIPIO,
    LT.COD_UNICO_ENDERECO,
    CN.ID_QUADRA,
    LT.NOM_LOGRADOURO,
    LT.NUM_ENDERECO,
    NOM_LOGRADOURO_ADJACENTE,
    DIM_TESTADA,
    DIM_PROFUNDIDADE
FROM CN_PONTOS_UNICOS_ CN
JOIN CI_LOTES_ LT
	ON (CN.COD_MUNICIPIO = LT.COD_MUNICIPIO)
		AND (CN.SC_ID_LOGRADOURO = LT.SC_ID_LOGRADOURO)
        AND (CN.NUM_ENDERECO = LT.NUM_ENDERECO)
;


-- Atualizando as faces em CI_FACE
INSERT INTO CI_FACES (
    ID_FACE, 
    COD_MUNICIPIO, 
    ID_QUADRA, 
    SC_ID_LOGRADOURO, 
    QTD_LOTES, 
    DIM_FACE
)
SELECT 
    CONCAT(LT.COD_MUNICIPIO, LT.NUM_QUADRA, LG.SC_ID_LOGRADOURO) AS ID_FACE,
    LT.COD_MUNICIPIO, 
    LT.NUM_QUADRA AS ID_QUADRA, 
    LG.SC_ID_LOGRADOURO,
    COUNT(*) AS QTD_LOTES,           -- Conta quantos lotes existem nesta face
    SUM(LT.DIM_TESTADA) AS DIM_FACE  -- Soma a testada total da face
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG 
    ON 
		(LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
    AND
		(LT.COD_MUNICIPIO = LG.COD_MUNICIPIO)
GROUP BY 
    LT.COD_MUNICIPIO, 
    LT.NUM_QUADRA, 
    LG.SC_ID_LOGRADOURO;

-- Criando a tabela CI_QUADRAS
    CREATE TABLE IF NOT EXISTS CI_QUADRAS (
      ID_QUADRA         VARCHAR(50),
      COD_MUNICIPIO 	VARCHAR(7),
      SC_ID_QUADRA 		VARCHAR(250),
      QTD_PONTOS 		INT,
      AREA 				DECIMAL(10,2)
    );
    
-- Preenchendo CI_QUADRAS
-- Aumenta o limite de caracteres para evitar corte no JSON em quadras grandes
SET SESSION group_concat_max_len = 10000;

INSERT INTO CI_QUADRAS (
    ID_QUADRA, 
    COD_MUNICIPIO, 
    SC_ID_QUADRA, 
    QTD_PONTOS, 
    AREA
)
SELECT 
    ID_QUADRA,
    COD_MUNICIPIO,
    -- Constrói o array usando aspas duplas literais
    CONCAT('["', 
        GROUP_CONCAT(SC_ID_LOGRADOURO ORDER BY SC_ID_LOGRADOURO SEPARATOR '","'), 
    '"]') AS SC_ID_QUADRA,
    SUM(QTD_LOTES) AS QTD_PONTOS,
    0.00 AS AREA
FROM CI_FACES
GROUP BY 
    COD_MUNICIPIO, 
    ID_QUADRA;
    
-- Selecionar a quadra para estudos
SELECT 
    ID_QUADRA, 
    COD_MUNICIPIO, 
    SC_ID_QUADRA, 
    QTD_PONTOS
FROM CI_QUADRAS
WHERE SC_ID_QUADRA LIKE '%9003F37C%'
  AND SC_ID_QUADRA LIKE '%F0D334EC%'
  AND SC_ID_QUADRA LIKE '%F54DE0AF%';
  
SELECT 
    F.ID_FACE,
    F.ID_QUADRA,
    F.SC_ID_LOGRADOURO,
    L.CI_NOM_LOGRADOURO,
    F.QTD_LOTES,
    F.DIM_FACE,
    L.COORDS
FROM CI_FACES F
JOIN CI_LOGRADOUROS L 
    ON F.SC_ID_LOGRADOURO = L.SC_ID_LOGRADOURO
WHERE 
    F.ID_QUADRA = '410450105000001P012'
ORDER BY 
    L.CI_NOM_LOGRADOURO;
    
CREATE TABLE `CI_ADJACENTES` (
  `ID_FACE` varchar(50) DEFAULT NULL,
  `COD_MUNICIPIO` varchar(7) DEFAULT NULL,
  `ID_QUADRA` varchar(50) DEFAULT NULL,
  `SC_ID_LOGRADOURO` varchar(8) DEFAULT NULL,
  `QTD_LOTES` int(11) DEFAULT NULL,
  `DIM_FACE` decimal(6,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

