SELECT * FROM smuu.CI_QUADRAS;

-- ***************************************************************
-- CI_ADJACENTES
-- CI_ADJACENTES
-- CI_ADJACENTES
-- ***************************************************************    
-- Criação da tabela CI_ADJACENTES
CREATE TABLE IF NOT EXISTS CI_ADJACENTES (
	ID_FACE           VARCHAR(65),
	COD_MUNICIPIO     VARCHAR(7),
	ID_QUADRA         VARCHAR(50),
	SC_ID_LOGRADOURO  VARCHAR(8),
	DIM_ADJACENTE     DECIMAL(6,2)                                                                                                   
);

-- Povoamento de CI_ADJACENTES
INSERT INTO CI_ADJACENTES (
  ID_FACE, 
  COD_MUNICIPIO, 
  ID_QUADRA, 
  SC_ID_LOGRADOURO, 
  DIM_ADJACENTE
)
SELECT 
  CONCAT(LT.COD_MUNICIPIO, ";", LT.NUM_QUADRA, ";", LG.SC_ID_LOGRADOURO) AS ID_FACE,
  LT.COD_MUNICIPIO, 
  LT.NUM_QUADRA AS ID_QUADRA, 
  LG.SC_ID_LOGRADOURO,
  SUM(LT.DIM_PROFUNDIDADE) AS DIM_ADJACENTE
FROM (
  /* Subconsulta para eliminar duplicatas de COD_UNICO_ENDERECO */
  SELECT DISTINCT 
	  COD_MUNICIPIO, 
	  NUM_QUADRA, 
	  NOM_LOGRADOURO_ADJACENTE, 
	  COD_UNICO_ENDERECO, 
	  DIM_PROFUNDIDADE
  FROM CI_LOTES
  WHERE 
	  NOM_LOGRADOURO_ADJACENTE <> ""
) LT
JOIN CI_LOGRADOUROS LG 
  ON (LT.NOM_LOGRADOURO_ADJACENTE = LG.CI_NOM_LOGRADOURO)
  AND (LT.COD_MUNICIPIO = LG.COD_MUNICIPIO)
GROUP BY 
  LT.COD_MUNICIPIO, 
  LT.NUM_QUADRA, 
  LG.SC_ID_LOGRADOURO;
  
-- Atualização de CI_FACES 
UPDATE CI_FACES F
INNER JOIN (
    SELECT 
        ID_FACE, 
        SUM(DIM_ADJACENTE) AS TOTAL_ADJACENTE
    FROM CI_ADJACENTES
    GROUP BY ID_FACE
) A ON F.ID_FACE = A.ID_FACE
SET F.DIM_FACE = F.DIM_FACE + A.TOTAL_ADJACENTE;