SELECT * FROM smuu.CI_LOTES 
;

SELECT * FROM smuu.CI_LOGRADOUROS
;

SELECT 
	DISTINCT 
    CONCAT(LT.COD_MUNICIPIO, NUM_QUADRA, SC_ID_LOGRADOURO) AS ID_FACE,
    LT.COD_MUNICIPIO, NUM_QUADRA, NOM_LOGRADOURO, SC_ID_LOGRADOURO
FROM CI_LOTES LT
JOIN
	CI_LOGRADOUROS LG
    ON 
		(LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
;

SELECT 
    CONCAT(LT.COD_MUNICIPIO, NUM_QUADRA, SC_ID_LOGRADOURO) AS ID_FACE,
    LT.COD_MUNICIPIO, 
    NUM_QUADRA, 
    NOM_LOGRADOURO, 
    SC_ID_LOGRADOURO,
    SUM(LT.DIM_TESTADA) AS TOTAL_TESTADA
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG
    ON (LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
GROUP BY 
    LT.COD_MUNICIPIO, 
    NUM_QUADRA, 
    NOM_LOGRADOURO, 
    SC_ID_LOGRADOURO
;
    
-- Atualizando as quadras em CI_LOTES
-- quando a ID_QUADRA não está disponível no cadastro municipal
-- Usar somente para fins acadêmicos
DROP TABLE IF EXISTS CI_LOTES_;
CREATE TEMPORARY TABLE CI_LOTES_
SELECT 
	LT.COD_MUNICIPIO,
    LT.COD_UNICO_ENDERECO,
    LT.NUM_QUADRA,
    LT.NOM_LOGRADOURO,
    LT.NUM_ENDERECO,
    NOM_LOGRADOURO_ADJACENTE,
    DIM_TESTADA,
    DIM_PROFUNDIDADE,
	LG.SC_ID_LOGRADOURO
FROM CI_LOTES LT
JOIN CI_LOGRADOUROS LG
	ON (LT.NOM_LOGRADOURO = LG.CI_NOM_LOGRADOURO)
;
SELECT *
FROM CI_LOTES_
;

CREATE TEMPORARY TABLE CN_PONTOS_UNICOS_
SELECT 
	PU.COD_MUNICIPIO,
    LG.NOM_LOGRADOURO,
    LG.SC_ID_LOGRADOURO,
    PU.NUM_ENDERECO,
    PU.ID_QUADRA
FROM CN_PONTOS_UNICOS PU
JOIN CN_LOGRADOUROS LG
	ON (PU.NOM_LOGRADOURO = LG.NOM_LOGRADOURO)
;
SELECT *
FROM CN_PONTOS_UNICOS_
;

SELECT
	LT.COD_MUNICIPIO,
    LT.COD_UNICO_ENDERECO,
    CN.ID_QUADRA,
    LT.NOM_LOGRADOURO,
    LT.NUM_ENDERECO,
    NOM_LOGRADOURO_ADJACENTE,
    DIM_TESTADA,
    DIM_PROFUNDIDADE
FROM CN_PONTOS_UNICOS_ CN
JOIN CI_LOTES_ LT
	ON (CN.COD_MUNICIPIO = LT.COD_MUNICIPIO)
		AND (CN.SC_ID_LOGRADOURO = LT.SC_ID_LOGRADOURO)
        AND (CN.NUM_ENDERECO = LT.NUM_ENDERECO)
;

cod_municipio;cod_unico_endereco;num_quadra;nom_logradouro;num_endereco;nom_logradouro_adjacente;dim_testada;dim_profundidade

