CREATE TABLE IF NOT EXISTS SC_QUADRAS (
	SC_ID_QUADRA 		VARCHAR(250),
	COD_MUNICIPIO 	  	VARCHAR(7),
	CI_ID_QUADRA       	VARCHAR(50),
	CN_ID_QUADRA        VARCHAR(19),
    ORDEM_FACES         VARCHAR(250),
    CENTROIDE           POINT
);

INSERT INTO SC_QUADRAS (
    SC_ID_QUADRA,
    COD_MUNICIPIO,
    CI_ID_QUADRA,
    CN_ID_QUADRA,
    ORDEM_FACES,
    CENTROIDE
)
SELECT 
    cn.SC_ID_QUADRA,
    cn.COD_MUNICIPIO,
    ci.ID_QUADRA AS CI_ID_QUADRA,
    cn.ID_QUADRA AS CN_ID_QUADRA,
    cn.ORDEM_FACES,
    cn.CENTROIDE
FROM CN_QUADRAS cn
INNER JOIN CI_QUADRAS ci 
    ON cn.SC_ID_QUADRA = ci.SC_ID_QUADRA 
    AND cn.COD_MUNICIPIO = ci.COD_MUNICIPIO;